### PR TITLE
SB-0001: initial release

### PR DESCRIPTION
**Pull request by bsubhamay**
## Describe your changes

Pull Request to merge the feature branch for initial release with main

## Issue ticket number and link

SB-0001

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Review by bsubhamay — COMMENTED** [review]
Code review done.

**Review by bsubhamay — COMMENTED** [review]
Code Review complete

**Review by bsubhamay-approver — APPROVED** [review]
Initial release looks good. Approved.

**Review by bsubhamay-approver — APPROVED** [review]
Approved

**Review by bsubhamay-approver — APPROVED** [review]

**Pull request merged**
